class ExampleData < ActiveRecord::Migration[5.0]
  def change
    algorithm = Rails.application.config.sisito.fetch(:digest)

    (1..100).flat_map {|i|
      [{timestamp: Date.today - rand(14).days, lhost: "mail.example.com", rhost: "mail.test1.example.com", alias: "foo#{i}@test1.example.com", listid: "", reason: "rejected",    action: "failed", subject: "hello",        messageid: "foo#{i}@xxx.mail", smtpagent: "MTA::Postfix", softbounce: "1", smtpcommand: "MAIL", destination: "test1.example.com", senderdomain: "example.com", feedbacktype: "", diagnosticcode: "553 #5.1.8 Domain of sender address <no-reply@example.com> does not exist", deliverystatus: "5.1.8", timezoneoffset: "+0900", addresser: "no-reply@example.com", addresseralias: "no-reply@example.com",     recipient: "foo#{i}@test1.example.com", digest: algorithm.hexdigest("foo#{i}@test1.example.com"), created_at: Date.today - rand(14).days, updated_at: Date.today - rand(14).days},
       {timestamp: Date.today - rand(14).days, lhost: "mail.example.com", rhost: "mail.test2.example.com", alias: "bar#{i}@test2.example.com", listid: "", reason: "filtered",    action: "failed", subject: "how are you?", messageid: "bar#{i}@xxx.mail", smtpagent: "MTA::Postfix", softbounce: "1", smtpcommand: "DATA", destination: "test2.example.com", senderdomain: "example.com", feedbacktype: "", diagnosticcode: "550 Unknown user bar#{i}@test2.example.com",                                deliverystatus: "5.0.0", timezoneoffset: "+0900", addresser: "no-reply@example.com", addresseralias: "no-reply+foo@example.com", recipient: "bar#{i}@test2.example.com", digest: algorithm.hexdigest("bar#{i}@test2.example.com"), created_at: Date.today - rand(14).days, updated_at: Date.today - rand(14).days},
       {timestamp: Date.today - rand(14).days, lhost: "mail.example.com", rhost: "mail.test3.example.com", alias: "zoo#{i}@test3.example.com", listid: "", reason: "blocked",     action: "failed", subject: "fine thanks",  messageid: "zoo#{i}@xxx.mail", smtpagent: "MTA::Postfix", softbounce: "1", smtpcommand: "DATA", destination: "test3.example.com", senderdomain: "example.com", feedbacktype: "", diagnosticcode: "554 5.7.1 Command rejected",                                                deliverystatus: "5.7.1", timezoneoffset: "+0900", addresser: "no-reply@example.com", addresseralias: "",                         recipient: "zoo#{i}@test3.example.com", digest: algorithm.hexdigest("zoo#{i}@test3.example.com"), created_at: Date.today - rand(14).days, updated_at: Date.today - rand(14).days},
       {timestamp: Date.today - rand(14).days, lhost: "mail.example.com", rhost: "mail.test4.example.com", alias: "baz#{i}@test4.example.com", listid: "", reason: "userunknown", action: "failed", subject: "good bye",     messageid: "baz#{i}@xxx.mail", smtpagent: "MTA::Postfix", softbounce: "0", smtpcommand: "RCPT", destination: "test4.example.com", senderdomain: "example.com", feedbacktype: "", diagnosticcode: "550 Requested action not taken: mailbox unavailable",                       deliverystatus: "5.0.0", timezoneoffset: "+0900", addresser: "no-reply@example.com", addresseralias: "no-reply+bar@example.com", recipient: "baz#{i}@test4.example.com", digest: algorithm.hexdigest("baz#{i}@test4.example.com"), created_at: Date.today - rand(14).days, updated_at: Date.today - rand(14).days},
       {timestamp: Date.today - rand(14).days, lhost: "mail.example.com", rhost: "mail.test5.example.com", alias: "bar#{i}@test5.example.com", listid: "", reason: "filtered",    action: "failed", subject: "how are you?", messageid: "bar#{i}@xxx.mail", smtpagent: "MTA::Postfix", softbounce: "1", smtpcommand: "DATA", destination: "test2.example.com", senderdomain: "example.com", feedbacktype: "", diagnosticcode: "550 Unknown user bar#{i}@test2.example.com",                                deliverystatus: "5.0.0", timezoneoffset: "+0900", addresser: "no-reply@example.com", addresseralias: "no-reply@example.com",     recipient: "bar#{i}@test2.example.com", digest: algorithm.hexdigest("bar#{i}@test2.example.com"), created_at: Date.today - rand(14).days, updated_at: Date.today - rand(14).days},
       {timestamp: Date.today - rand(14).days, lhost: "mail.example.com", rhost: "mail.test6.example.com", alias: "zoo#{i}@test6.example.com", listid: "", reason: "blocked",     action: "failed", subject: "fine thanks",  messageid: "zoo#{i}@xxx.mail", smtpagent: "MTA::Postfix", softbounce: "1", smtpcommand: "DATA", destination: "test3.example.com", senderdomain: "example.com", feedbacktype: "", diagnosticcode: "554 5.7.1 Command rejected",                                                deliverystatus: "5.7.1", timezoneoffset: "+0900", addresser: "no-reply@example.com", addresseralias: "no-reply+zoo@example.com", recipient: "zoo#{i}@test3.example.com", digest: algorithm.hexdigest("zoo#{i}@test3.example.com"), created_at: Date.today - rand(14).days, updated_at: Date.today - rand(14).days},
       {timestamp: Date.today - rand(14).days, lhost: "mail.example.com", rhost: "mail.test7.example.com", alias: "baz#{i}@test7.example.com", listid: "", reason: "userunknown", action: "failed", subject: "good bye",     messageid: "baz#{i}@xxx.mail", smtpagent: "MTA::Postfix", softbounce: "0", smtpcommand: "RCPT", destination: "test4.example.com", senderdomain: "example.com", feedbacktype: "", diagnosticcode: "550 Requested action not taken: mailbox unavailable",                       deliverystatus: "5.0.0", timezoneoffset: "+0900", addresser: "no-reply@example.com", addresseralias: "",                         recipient: "baz#{i}@test4.example.com", digest: algorithm.hexdigest("baz#{i}@test4.example.com"), created_at: Date.today - rand(14).days, updated_at: Date.today - rand(14).days},
      ]
    }.each do |row|
      BounceMail.create!(row)
    end

    [{recipient: "zoo1@test3.example.com", senderdomain: "example.com", created_at: Date.today - 3.day, updated_at: Date.today - 3.day},
     {recipient: "baz1@test4.example.com", senderdomain: "example.com", created_at: Date.today - 2.day, updated_at: Date.today - 2.day},
     {recipient: "foo1@test1.example.com", senderdomain: "example.com", created_at: Date.today        , updated_at: Date.today        },
    ].each do |row|
      WhitelistMail.create!(row)
    end
  end
end
