class ExampleData < ActiveRecord::Migration[5.0]
  def change
    (1..100).flat_map {|i|
      [{timestamp: "2017-01-26", lhost: "mail.example.com", rhost: "mail.test1.example.com", alias: "foo#{i}@test1.example.com", listid: "", reason: "rejected",    action: "failed", subject: "hello",        messageid: "foo#{i}@xxx.mail", smtpagent: "MTA::Postfix", softbounce: "1", smtpcommand: "MAIL", destination: "test1.example.com", senderdomain: "example.com", feedbacktype: "", diagnosticcode: "553 #5.1.8 Domain of sender address <no-reply@example.com> does not exist", deliverystatus: "5.1.8", timezoneoffset: "+0900", addresser: "no-reply@example.com", recipient: "foo#{i}@test1.example.com", digest: "ddcc62883c17a4e4b734c69eb20af81670e04eb5", created_at: "2017-01-26", updated_at: "2017-01-26"},
       {timestamp: "2017-01-27", lhost: "mail.example.com", rhost: "mail.test2.example.com", alias: "bar#{i}@test2.example.com", listid: "", reason: "filtered",    action: "failed", subject: "how are you?", messageid: "bar#{i}@xxx.mail", smtpagent: "MTA::Postfix", softbounce: "1", smtpcommand: "DATA", destination: "test2.example.com", senderdomain: "example.com", feedbacktype: "", diagnosticcode: "550 Unknown user bar#{i}@test2.example.com",                                deliverystatus: "5.0.0", timezoneoffset: "+0900", addresser: "no-reply@example.com", recipient: "bar#{i}@test2.example.com", digest: "e7d7c36434cba814ad7c4780bdfa947ef035df21", created_at: "2017-01-27", updated_at: "2017-01-27"},
       {timestamp: "2017-01-28", lhost: "mail.example.com", rhost: "mail.test3.example.com", alias: "zoo#{i}@test3.example.com", listid: "", reason: "blocked",     action: "failed", subject: "fine thanks",  messageid: "zoo#{i}@xxx.mail", smtpagent: "MTA::Postfix", softbounce: "1", smtpcommand: "DATA", destination: "test3.example.com", senderdomain: "example.com", feedbacktype: "", diagnosticcode: "554 5.7.1 Command rejected",                                                deliverystatus: "5.7.1", timezoneoffset: "+0900", addresser: "no-reply@example.com", recipient: "zoo#{i}@test3.example.com", digest: "53d68473838955f4aa06b88a8c14f46d93154953", created_at: "2017-01-28", updated_at: "2017-01-28"},
       {timestamp: "2017-01-29", lhost: "mail.example.com", rhost: "mail.test4.example.com", alias: "baz#{i}@test4.example.com", listid: "", reason: "userunknown", action: "failed", subject: "good bye",     messageid: "baz#{i}@xxx.mail", smtpagent: "MTA::Postfix", softbounce: "0", smtpcommand: "RCPT", destination: "test4.example.com", senderdomain: "example.com", feedbacktype: "", diagnosticcode: "550 Requested action not taken: mailbox unavailable",                       deliverystatus: "5.0.0", timezoneoffset: "+0900", addresser: "no-reply@example.com", recipient: "baz#{i}@test4.example.com", digest: "842086c3acd160117478119ae29e77dc29d2342f", created_at: "2017-01-29", updated_at: "2017-01-29"},
      ]
    }.each do |row|
      BounceMail.create!(row)
    end
  end
end
